package net.gabriele333.gabrielequests.client.structure.twilight;

import net.gabriele333.gabrielequests.client.render.BlockStates;
import net.minecraft.world.level.block.state.BlockState;
import org.jetbrains.annotations.Nullable;

import java.util.Random;

/**
 * The hedge maze: a 51&#215;51 square of hedge corridors on a grass plot, with a firefly here
 * and there and jack-o'-lanterns at the four entrances.
 *
 * <p>The maze is generated by the same algorithm the mod uses, ported from {@code TFMaze}
 * and {@code HedgeMazeComponent}: a 16&#215;16 cell grid, five 3&#215;3 rooms carved into it
 * at least three cells apart, then a recursive-backtracker carve from cell (0,0), retried
 * until every cell has been reached, then four exits punched through the outer wall. The
 * grid is written out with Twilight Forest's own spacing - one-block wall posts on the even
 * coordinates, two-block corridors between them, three blocks tall on three blocks of
 * mazestone footing - which is what makes the result read as <em>the</em> hedge maze rather
 * than as a maze.</p>
 *
 * <p>Two things the mod does that this does not: the canopy trees it grows at the corner
 * posts (they come from a configured feature, which needs world generation to run and would
 * tower over the maze in an icon anyway), and the spawners and chests inside the rooms.</p>
 */
final class HedgeMazeBuilder {

    /** Cells per side, and the block footprint that follows from it - both the mod's. */
    private static final int CELLS = 16;
    private static final int RADIUS = (CELLS / 2 * 3) + 1;
    private static final int DIAMETER = 2 * RADIUS;

    /** The mod's maze settings for this structure: 2-block corridors, 3 tall, 3 of footing. */
    private static final int ODD_BIAS = 2;
    private static final int EVEN_BIAS = 1;
    private static final int TALL = 3;
    private static final int ROOTS = 3;
    private static final float TORCH_RARITY = 0.75F;

    /** Cell values, straight from {@code TFMaze}. */
    private static final int OUT_OF_BOUNDS = Integer.MIN_VALUE;
    private static final int ROOM = 5;

    /** Guard on the "carve until every cell is reachable" retry, which is a random process. */
    private static final int MAX_ATTEMPTS = 32;

    private final int rawWidth = CELLS * 2 + 1;
    private final int rawDepth = CELLS * 2 + 1;
    private final int[] storage = new int[rawWidth * rawDepth];
    private final Random random;

    private HedgeMazeBuilder(Random random) {
        this.random = random;
    }

    @Nullable
    static TfScene build(String structureId, TfDefinition definition) {
        BlockState hedge = BlockStates.state("twilightforest:hedge");
        if (hedge == null) {
            return null; // no Twilight Forest, no hedge maze
        }
        BlockState footing = BlockStates.state("twilightforest:mazestone");
        BlockState firefly = BlockStates.state("twilightforest:firefly");
        BlockState grass = BlockStates.state("minecraft:grass_block");

        TfScene scene = new TfScene(structureId);
        HedgeMazeBuilder maze = new HedgeMazeBuilder(scene.random());
        maze.carve();

        // Grass first, so the maze's mazestone footing cuts into it exactly as in the world.
        for (int x = 0; x <= DIAMETER; x++) {
            for (int z = 0; z <= DIAMETER; z++) {
                scene.set(x, -1, z, grass);
            }
        }
        maze.copyInto(scene, hedge, footing, firefly);
        placeLanterns(scene);
        return scene;
    }

    /** The four pairs of jack-o'-lanterns flanking the entrances, at the mod's coordinates. */
    private static void placeLanterns(TfScene scene) {
        BlockState lantern = BlockStates.state("minecraft:jack_o_lantern");
        if (lantern == null) {
            return;
        }
        // A jack-o'-lantern faces the way it was placed from, so the ones on the west edge
        // look east, and so on round the plot.
        BlockState west = BlockStates.with(lantern, "facing", "east");
        BlockState east = BlockStates.with(lantern, "facing", "west");
        BlockState north = BlockStates.with(lantern, "facing", "south");
        BlockState south = BlockStates.with(lantern, "facing", "north");
        scene.set(0, 0, 24, west);
        scene.set(0, 0, 29, west);
        scene.set(DIAMETER, 0, 24, east);
        scene.set(DIAMETER, 0, 29, east);
        scene.set(24, 0, 0, north);
        scene.set(29, 0, 0, north);
        scene.set(24, 0, DIAMETER, south);
        scene.set(29, 0, DIAMETER, south);
    }

    // ---- the maze proper ------------------------------------------------------------

    private void carve() {
        int rooms = CELLS / 3;
        int[] placed = new int[rooms * 2];
        for (int attempt = 0; attempt < MAX_ATTEMPTS && !allCellsVisited(); attempt++) {
            resetCells();
            for (int i = 0; i < rooms; i++) {
                int rx = 0;
                int rz = 0;
                // Bounded, unlike the mod's open do/while: this runs on the render thread, so
                // a seed that happens to keep drawing occupied spots must cost a missing room,
                // never a frozen client.
                for (int tries = 0; tries < 64; tries++) {
                    rx = random.nextInt(CELLS - 2) + 1;
                    rz = random.nextInt(CELLS - 2) + 1;
                    if (!isNearRoom(rx, rz, placed)) {
                        break;
                    }
                }
                carveRoom(rx, rz);
                placed[i * 2] = rx;
                placed[i * 2 + 1] = rz;
            }
            backtrack(0, 0);
        }
        addFourExits();
    }

    /** Writes the carved grid out as blocks, at the mod's spacing. */
    private void copyInto(TfScene scene, BlockState wall, @Nullable BlockState footing,
                          @Nullable BlockState torch) {
        int step = EVEN_BIAS + ODD_BIAS;
        for (int x = 0; x < rawWidth; x++) {
            for (int z = 0; z < rawDepth; z++) {
                if (getRaw(x, z) != 0) { // anything but 0 has been carved away
                    continue;
                }
                int mx = 1 + (x / 2 * step);
                int mz = 1 + (z / 2 * step);
                if (isEven(x) && isEven(z)) {
                    column(scene, mx, mz, wall, footing);
                } else if (isEven(x)) {
                    for (int odd = 1; odd <= ODD_BIAS; odd++) {
                        column(scene, mx, mz + odd, wall, footing);
                    }
                } else if (isEven(z)) {
                    for (int odd = 1; odd <= ODD_BIAS; odd++) {
                        column(scene, mx + odd, mz, wall, footing);
                    }
                }
            }
        }
        // Fireflies go in afterwards, on the wall posts that are not part of a straight run -
        // the mod's rule, and the reason they end up marking junctions and dead ends.
        for (int x = 0; x < rawWidth; x++) {
            for (int z = 0; z < rawDepth; z++) {
                if (getRaw(x, z) == 0 && isEven(x) && isEven(z) && shouldTorch(x, z)) {
                    scene.set(1 + (x / 2 * step), 1, 1 + (z / 2 * step), torch);
                }
            }
        }
    }

    private void column(TfScene scene, int x, int z, BlockState wall, @Nullable BlockState footing) {
        for (int y = 0; y < TALL; y++) {
            scene.set(x, y, z, wall);
        }
        for (int y = 1; y <= ROOTS; y++) {
            scene.set(x, -y, z, footing);
        }
    }

    private boolean shouldTorch(int rx, int rz) {
        if (getRaw(rx + 1, rz) == OUT_OF_BOUNDS || getRaw(rx - 1, rz) == OUT_OF_BOUNDS
                || getRaw(rx, rz + 1) == OUT_OF_BOUNDS || getRaw(rx, rz - 1) == OUT_OF_BOUNDS) {
            return false;
        }
        if ((getRaw(rx + 1, rz) == 0 && getRaw(rx - 1, rz) == 0)
                || (getRaw(rx, rz + 1) == 0 && getRaw(rx, rz - 1) == 0)) {
            return false;
        }
        return random.nextFloat() <= TORCH_RARITY;
    }

    /** A 3&#215;3-cell room with an opening on each side. */
    private void carveRoom(int cx, int cz) {
        int rx = cx * 2 + 1;
        int rz = cz * 2 + 1;
        for (int i = -2; i <= 2; i++) {
            for (int j = -2; j <= 2; j++) {
                putRaw(rx + i, rz + j, ROOM);
            }
        }
        if (getRaw(rx, rz + 4) != OUT_OF_BOUNDS) {
            putRaw(rx, rz + 3, ROOM);
        }
        if (getRaw(rx, rz - 4) != OUT_OF_BOUNDS) {
            putRaw(rx, rz - 3, ROOM);
        }
        if (getRaw(rx + 4, rz) != OUT_OF_BOUNDS) {
            putRaw(rx + 3, rz, ROOM);
        }
        if (getRaw(rx - 4, rz) != OUT_OF_BOUNDS) {
            putRaw(rx - 3, rz, ROOM);
        }
    }

    private boolean isNearRoom(int cx, int cz, int[] placed) {
        if (cx == 1 && cz == 1) { // would cover the corner the carve starts from
            return true;
        }
        for (int i = 0; i < placed.length / 2; i++) {
            int rx = placed[i * 2];
            int rz = placed[i * 2 + 1];
            if (rx == 0 && rz == 0) {
                continue;
            }
            if (Math.abs(cx - rx) < 3 && Math.abs(cz - rz) < 3) {
                return true;
            }
        }
        return false;
    }

    private void addFourExits() {
        int hx = rawWidth / 2 + 1;
        int hz = rawDepth / 2 + 1;
        putRaw(hx, 0, ROOM);
        putRaw(hx, rawDepth - 1, ROOM);
        putRaw(0, hz, ROOM);
        putRaw(rawWidth - 1, hz, ROOM);
    }

    /**
     * Recursive backtracker: mark the cell, pick a random unvisited neighbour, knock the wall
     * between them down, recurse - then come back and try this cell twice more, which is what
     * fills the grid in rather than leaving one long snake.
     */
    private void backtrack(int sx, int sz) {
        putCell(sx, sz, 1);
        int unvisited = 0;
        if (cellIs(sx + 1, sz, 0)) {
            unvisited++;
        }
        if (cellIs(sx - 1, sz, 0)) {
            unvisited++;
        }
        if (cellIs(sx, sz + 1, 0)) {
            unvisited++;
        }
        if (cellIs(sx, sz - 1, 0)) {
            unvisited++;
        }
        if (unvisited == 0) {
            return;
        }
        int roll = random.nextInt(unvisited);
        int dx = Integer.MIN_VALUE;
        int dz = Integer.MIN_VALUE;
        if (cellIs(sx + 1, sz, 0)) {
            if (roll == 0) {
                dx = sx + 1;
                dz = sz;
            }
            roll--;
        }
        if (cellIs(sx - 1, sz, 0)) {
            if (roll == 0) {
                dx = sx - 1;
                dz = sz;
            }
            roll--;
        }
        if (cellIs(sx, sz + 1, 0)) {
            if (roll == 0) {
                dx = sx;
                dz = sz + 1;
            }
            roll--;
        }
        if (cellIs(sx, sz - 1, 0) && roll == 0) {
            dx = sx;
            dz = sz - 1;
        }
        if (dx == Integer.MIN_VALUE) {
            return; // no neighbour selected; nothing to carve
        }
        putWall(sx, sz, dx, dz, 2);
        backtrack(dx, dz);
        backtrack(sx, sz);
        backtrack(sx, sz);
    }

    // ---- grid storage ---------------------------------------------------------------
    // Cells live at the odd raw coordinates and the walls between them at the even ones,
    // which is what lets one array hold both.

    private boolean allCellsVisited() {
        for (int x = 0; x < CELLS; x++) {
            for (int z = 0; z < CELLS; z++) {
                if (getCell(x, z) == 0) {
                    return false;
                }
            }
        }
        return true;
    }

    private void resetCells() {
        for (int x = 0; x < CELLS; x++) {
            for (int z = 0; z < CELLS; z++) {
                putCell(x, z, 0);
            }
        }
    }

    private int getCell(int x, int z) {
        return getRaw(x * 2 + 1, z * 2 + 1);
    }

    private void putCell(int x, int z, int value) {
        putRaw(x * 2 + 1, z * 2 + 1, value);
    }

    private boolean cellIs(int x, int z, int value) {
        return getCell(x, z) == value;
    }

    private void putWall(int sx, int sz, int dx, int dz, int value) {
        if (dx == sx + 1 && dz == sz) {
            putRaw(sx * 2 + 2, sz * 2 + 1, value);
        } else if (dx == sx - 1 && dz == sz) {
            putRaw(sx * 2, sz * 2 + 1, value);
        } else if (dx == sx && dz == sz + 1) {
            putRaw(sx * 2 + 1, sz * 2 + 2, value);
        } else if (dx == sx && dz == sz - 1) {
            putRaw(sx * 2 + 1, sz * 2, value);
        }
    }

    private int getRaw(int x, int z) {
        if (x < 0 || x >= rawWidth || z < 0 || z >= rawDepth) {
            return OUT_OF_BOUNDS;
        }
        return storage[z * rawWidth + x];
    }

    private void putRaw(int x, int z, int value) {
        if (x >= 0 && x < rawWidth && z >= 0 && z < rawDepth) {
            storage[z * rawWidth + x] = value;
        }
    }

    private static boolean isEven(int n) {
        return n % 2 == 0;
    }
}
